name: mobile_ung
description: "DocFlow"
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: 7.8.4

  #decoration
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  #state management
  get: ^4.6.6

  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  flutter_screenutil: ^5.9.0
  xml: ^6.3.0
  path_drawing: ^1.0.1

  share_plus: ^9.0.0
  flutter_riverpod: ^2.5.1
  easy_localization: ^3.0.7
  omega_dio_logger: ^1.2.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

  #pie_chart:
  pie_chart: ^5.4.0
  d_chart: ^2.8.0

  #table_calendar
  table_calendar: ^3.1.2

  countup: ^0.1.4
  url_launcher: ^6.2.4
  path_provider: ^2.1.4
  open_filex: ^4.5.0

  shared_preferences: any
  package_info_plus: any
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: 7.3.2
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7
  injectable_generator: ^2.6.1
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"